# Основные настройки
target-version = "py312"
line-length = 120
indent-width = 4

# Директории для сканирования
src = ["src", "tests"]
include = ["*.py", "*.pyi"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "migrations",
    "alembic/versions",
]

# Исправления автоматически (по умолчанию false для check команды)
fix = false

[lint]
# Настройка правил
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E",
    "W",
    # McCabe complexity
    "C90",
    # isort
    "I",
    # pep8-naming
    "N",
    # pydocstyle
    "D",
    # pyupgrade
    "UP",
    # flake8-2020
    "YTT",
    # flake8-annotations
    "ANN",
    # flake8-async
    "ASYNC",
    # flake8-bandit
    "S",
    # flake8-blind-except
    "BLE",
    # flake8-boolean-trap
    "FBT",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-commas
    "COM",
    # flake8-comprehensions
    "C4",
    # flake8-datetimez
    "DTZ",
    # flake8-debugger
    "T10",
    # flake8-django
    "DJ",
    # flake8-errmsg
    "EM",
    # flake8-executable
    "EXE",
    # flake8-future-annotations
    "FA",
    # flake8-implicit-str-concat
    "ISC",
    # flake8-import-conventions
    "ICN",
    # flake8-logging-format
    "G",
    # flake8-no-pep420
    "INP",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
    # flake8-pyi
    "PYI",
    # flake8-pytest-style
    "PT",
    # flake8-quotes
    "Q",
    # flake8-raise
    "RSE",
    # flake8-return
    "RET",
    # flake8-self
    "SLF",
    # flake8-simplify
    "SIM",
    # flake8-tidy-imports
    "TID",
    # flake8-type-checking
    "TCH",
    # flake8-unused-arguments
    "ARG",
    # flake8-use-pathlib
    "PTH",
    # pandas-vet
    "PD",
    # pygrep-hooks
    "PGH",
    # Pylint
    "PL",
    # tryceratops
    "TRY",
    # flynt
    "FLY",
    # NumPy-specific rules
    "NPY",
    # Airflow
    "AIR",
    # Perflint
    "PERF",
    # refurb
    "FURB",
    # flake8-logging
    "LOG",
    # Ruff-specific rules
    "RUF",
]

ignore = [
    # Отключаем некоторые правила для FastAPI
    "ANN401",  # Dynamically typed expressions (typing.Any)
    "B008",    # Do not perform function calls in argument defaults (FastAPI Depends)
    "S101",    # Use of `assert` detected
    "D100",    # Missing docstring in public module
    "D101",    # Missing docstring in public class
    "D102",    # Missing docstring in public method
    "D103",    # Missing docstring in public function
    "D104",    # Missing docstring in public package
    "D105",    # Missing docstring in magic method
    "D107",    # Missing docstring in `__init__`
    "COM812",  # Trailing comma missing
    "COM819",  # Trailing comma prohibited
    "E501",    # Line too long (handled by formatter)
    "N802",    # Function name should be lowercase (для property методов в настройках)
    "PLR0913", # Too many arguments to function call
    "PLR2004", # Magic value used in comparison
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
    "SIM108",  # Use ternary operator instead of if-else-block
    "TRY003",  # Avoid specifying long messages outside the exception class
    "UP007",   # Use `X | Y` for type annotations (we use Python 3.12, but some tools don't support it yet)
    "F401",    # Unused imports
    "N818",    # Cunstom exceptions name must be end of Error
    "D415",    # Docstring must be end of dot
    "RUF023",  # __slots__ sorting
    "ANN204",  # Init dont have response type lol
    "INP001",  # Is part of an implicit namespace package
    "G004",
    "UP035",
    "I001",
    "ARG001",
    "Q000",
    "EM102",
    "TC001",
    "D212",
    "D205",
    "D211",
    "D201"
]

# Разрешить автоисправления
fixable = ["ALL"]
unfixable = []

# Конфигурация для конкретных правил
[lint.per-file-ignores]
"tests/**/*.py" = [
    "S101",     # Use of assert in tests
    "PLR2004",  # Magic value used in comparison
    "ANN001",   # Missing type annotation for function argument
    "ANN201",   # Missing return type annotation for public function
    "D",        # All docstring rules for tests
]

"src/infrastructure/database/migrations/**/*.py" = [
    "D",        # All docstring rules for migrations
    "ANN",      # All annotation rules for migrations
    "F401",     # Unused imports in migrations
]

"src/main.py" = [
    "D100",     # Missing docstring in public module
    "Q000",
    "UP006"
]

"src/settings.py" = [
    "D100",     # Missing docstring in public module
    "Q000",
    "UP006",
    "UP035",
    "I001"
]

"src/infrastructure/logger/logger.py" = [
    "DTZ005",
    "EM101",
    "TRY004",
    "UP008",
    "UP045",
    "ARG004"
]

"src/application/domain/objects/incomparable.py" = [
    "B024"
]

"src/application/domain/objects/sealed.py" = [
    "B024"
]

# Настройки для isort
[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-first-party = ["src"]
known-third-party = [
    "fastapi",
    "pydantic",
    "sqlalchemy",
    "alembic",
    "asyncpg",
    "redis",
    "celery",
    "pytest",
    "uvicorn",
    "granian",
]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder"
]

# Настройки для pydocstyle
[lint.pydocstyle]
convention = "google"

# Настройки для flake8-quotes
[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

# Настройки для flake8-bugbear
[lint.flake8-bugbear]
extend-immutable-calls = [
    "fastapi.Depends",
    "fastapi.Query",
    "fastapi.Path",
    "fastapi.Body",
    "fastapi.Header",
    "fastapi.Cookie",
    "fastapi.Form",
    "fastapi.File",
    "pydantic.Field",
]

# Настройки для flake8-type-checking
[lint.flake8-type-checking]
strict = true

# Настройки для pylint
[lint.pylint]
max-args = 10
max-branches = 15
max-returns = 8
max-statements = 60

# Настройки для McCabe complexity
[lint.mccabe]
max-complexity = 15

# Настройки форматирования
[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
