from src.application.domain.exceptions.immutable_attribute_error import ImmutableAttributeError
from src.application.domain.exceptions.incomparable_object_error import IncomparableObjectError
from src.application.domain.exceptions.sealed_class_error import SealedClassError
